name: iso9660
description: This library is a simple implementation of the iso9660 filesystem standard.
version: 0.0.1
repository: https://github.com/dahliaOS/iso9660

environment:
  sdk: ^3.4.0

dependencies:
  path: ^1.6.4
